apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: app01-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          - name: html-content
            mountPath: /usr/share/nginx/html
          - name: version-storage
            mountPath: /var/www/html/versions
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: html-content
          emptyDir: {}
        - name: version-storage
          persistentVolumeClaim:
            claimName: version-volume-claim
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen      80;
      server_name localhost;
    }

    location / {
      root    /var/www/html;
      index   index.html  index.htm;
    }

    error_page  500 502 503 504 /50x.html;
    location = /50x.html {
      root    /var/www/html
    }