apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: version-config
          mountPath: /var/www/html/versions/all-o24.version.txt
          subPath: 10-version.yaml
      volumes:
      - name: version-config
        configMap:
          name: outscan-gitops-version-config