apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        checksum/config: ${CONFIGMAP_CHECKSUM}
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: version-config
          mountPath: /var/www/html/versions/all-o24.version.txt
          subPath: all-o24.version.txt
      volumes:
      - name: version-config
        configMap:
          name: outscan-gitops-version-config
          items:
          - key: 10-version.yaml
            path: all-o24.version.txt