apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: false

resources:
  - deployment.yaml

configMapGenerator:
  - name: outscan-gitops-version-config
    files:
      - all-o24.version.txt