apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - deployment.yaml

configMapGenerator:
  - name: outscan-gitops-version-config
    files:
      - 10-version.yaml