apiVersion: batch/v1
kind: Job
metadata:
  name: update-version-job
  namespace: app01-volume
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    metadata:
        annotations:
          version: "1.55"
    spec:
      serviceAccountName: version-job-sa
      containers:
      - name: version-job
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          VERSION=$(kubectl -n app01-volume get pod --selector=job-name=update-version-job -o=jsonpath='{.items[0].metadata.annotations.version}')
          echo "system $VERSION" > /mnt/versions/all-o24.version.txt  # Ghi vào file trong volume
          echo "New version is: $VERSION"
        env:
        - name: VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
          - name: version-storage
            mountPath: /mnt/versions
      securityContext:
          runAsUser: 0  # Chạy container dưới user root
      volumes:
        - name: version-storage
          persistentVolumeClaim:
            claimName: version-volume-claim
      restartPolicy: OnFailure