apiVersion: batch/v1
kind: Job
metadata:
  name: update-version-job
  namespace: app01-volume
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      labels:
        app: version-update
    spec:
      containers:
      - name: version-job
        image: busybox
        env:
          - name: VERSION
            value: "1.62"
        command:
        - /bin/sh
        - -c
        - |
          echo "system: $VERSION" > /mnt/versions/all-o24.version.txt
          echo "New version is: $VERSION"
        volumeMounts:
          - name: version-storage
            mountPath: /mnt/versions
      securityContext:
        runAsUser: 0  # Run container as root user
      volumes:
        - name: version-storage
          persistentVolumeClaim:
            claimName: version-volume-claim  # Ensure this PVC exists
      restartPolicy: OnFailure
