apiVersion: batch/v1
kind: Job
metadata:
  name: update-version-job
  namespace: app01-volume
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
    spec:
      containers:
      - name: version-job
        image: busybox
        env:
          - name: VERSION
            value: "1.61"
        command:
        - /bin/sh
        - -c
        - |
          echo "system: $VERSION" > /mnt/versions/all-o24.version.txt  # Ghi vào file trong volume
          echo "New version is: $VERSION"
        volumeMounts:
          - name: version-storage
            mountPath: /mnt/versions
      securityContext:
          runAsUser: 0  # Chạy container dưới user root
      volumes:
        - name: version-storage
          persistentVolumeClaim:
            claimName: version-volume-claim
      restartPolicy: OnFailure
